export enum CreditEventType {
  SUBSCRIPTION_CREDIT_GRANT = 'SUBSCRIPTION_CREDIT_GRANT',
  VERIFICATION_DEDUCTION = 'VERIFICATION_DEDUCTION',
  SUBSCRIPTION_VERIFICATION_DEFERRED = 'SUBSCRIPTION_VERIFICATION_DEFERRED',
  DEFERRED_DEDUCTION_SETTLED = 'DEFERRED_DEDUCTION_SETTLED',
  CREDIT_EXPIRY = 'CREDIT_EXPIRY',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
}
