export enum LedgerEntryType {
  OPENING_BALANCE = 'OPENING_BALANCE',
  VERIFIED_DEPOSIT = 'VERIFIED_DEPOSIT',
  MANUAL_DEPOSIT = 'MANUAL_DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  POSITIVE_CORRECTION = 'POSITIVE_CORRECTION',
  NEGATIVE_CORRECTION = 'NEGATIVE_CORRECTION',
  REVERSAL = 'REVERSAL',
}

export type LedgerDirection = 'CREDIT' | 'DEBIT';
