export enum PendingRecheckStatus {
  SCHEDULED = 'SCHEDULED',
  CLAIMED = 'CLAIMED',
  WAITING_CREDITS = 'WAITING_CREDITS',
  PAUSED_BRANCH = 'PAUSED_BRANCH',
  PAUSED_PROVIDER = 'PAUSED_PROVIDER',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
